# Generated by Django 3.2.4 on 2022-08-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetFor', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('fiscalYear', models.CharField(max_length=128)),
                ('indicators', models.CharField(max_length=128)),
                ('budgetType', models.CharField(max_length=128)),
                ('value', models.IntegerField()),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='scheme.resourceindex')),
            ],
            options={
                'db_table': 'Grants',
            },
        ),
    ]
