# Generated by Django 3.2.4 on 2022-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceindex',
            name='file_name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
