# Generated by Django 3.2.4 on 2022-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_resourceindex_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceindex',
            name='file_name',
            field=models.FileField(upload_to='csv'),
        ),
    ]
