# Generated by Django 3.2.4 on 2022-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0004_alter_resourceindex_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grants',
            name='value',
            field=models.CharField(max_length=128),
        ),
    ]
