# Generated by Django 3.2.4 on 2022-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0005_alter_grants_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceindex',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resourceindex',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
