# Generated by Django 3.2.4 on 2022-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0006_auto_20220803_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceindex',
            name='metadata_file',
            field=models.FileField(blank=True, default=None, upload_to='csv'),
        ),
    ]
