# Generated by Django 3.2.4 on 2022-08-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_resourceindex_metadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceindex',
            name='metadata_file',
            field=models.FileField(blank=True, default=None, upload_to='metadata'),
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='scheme.resourceindex')),
            ],
            options={
                'db_table': 'Metadata',
            },
        ),
    ]
