# Generated by Django 3.2.4 on 2022-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0011_resourceindex_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceindex',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
