# Generated by Django 3.2.4 on 2022-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0012_alter_resourceindex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceindex',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
